### ISSUE TITLE
System.ArgumentOutOfRangeException using: node20' is not supported

### ISSUE THREAD

**Issue by neseleznev** [aws-actions/configure-aws-credentials#920]
### Describe the bug

After upgrading to v4, we have the exception from time to time

### Expected Behavior

I expect it to work.
We have 15 similar jobs in the workflow which run in parallel.
Sometimes, one of them fails with the exception.
A retry helps

### Current Behavior

```
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node20' is not supported, use 'docker', 'node12' or 'node16' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load aws-actions/configure-aws-credentials/v4/action.yml
```

### Reproduction Steps

```yml
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ***
        role-to-assume: ***
```

**Comment by peterwoodworth** [comment]
What runner are you using in the cases that it fails?

**Comment by neseleznev** [comment]
> What runner are you using in the cases that it fails?

It's self-hosted if this matters. JFYI, there are 15 parallel jobs in the same configuration, which run in parallel

**Comment by peterwoodworth** [comment]
As far as I'm aware, GitHub self hosted runners should update automatically. So I doubt that it's your runner version being out of date, but I'm also not sure why else this would be occurring since `node20` is a valid value - else it would be failing every time.

**Comment by tim-finnigan** [comment]
How often does this issue occur? Can you share any steps for consistently reproducing it?

**Comment by neseleznev** [comment]
> How often does this issue occur? Can you share any steps for consistently reproducing it?

From what I faced, it had happened 4 times in the past few weeks (since the action version upgrade).
I have no steps to reproduce it

**Comment by AkshataHegde-ZS** [comment]
We are also facing the same issue with the `aws-actions/configure-aws-credentials@v4` in windows self-hosted runner. For us, the issue is not intermittent, but happening with every time the action runs.

**Comment by neseleznev** [comment]
> Node20 support was added in [actions/runner@2.311.0](https://github.com/actions/runner/releases/tag/v2.311.0) 

I checked the failed runner. Indeed, it had an older version than the required
```
Current runner version: '2.299.1'
```

Thank you!
